
import jQuery from 'jquery/src/core';
import 'jquery/src/css';
import 'jquery/src/data';
import 'jquery/src/event';
import 'jquery/src/wrap';
import 'jquery/src/manipulation';
import 'jquery/src/offset';
import 'jquery/src/effects';
import 'jquery/src/effects/animatedSelector';
import 'jquery/src/css/hiddenVisibleSelectors';
import 'jquery/src/event/focusin';
import 'jquery/src/event/alias';
import 'jquery/src/event/trigger';
import 'jquery/src/attributes';
import 'jquery/src/core/init';
import 'jquery/src/core/parseHTML';
window["$"] = jQuery;
null;
export = $;