// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f06cd8787ed3f9b92024a9c6b5eb5364d399bdb4/i18next-xhr-backend/i18next-xhr-backend.d.ts
declare module 'i18next-xhr-backend' {

    interface Interpolator {
        interpolate: () => string
    }
    interface Services {
        interpolator: Interpolator
    }

    interface BackendOptions {
        loadPath?: string | Function,
        addPath?:  string,
        allowMultiLoading?: boolean,
        parse?: Function,
        crossDomain?: boolean,
        withCredentials?: boolean,
        ajax?: Function
    }

    export default class Backend {
        type: 'backend';
        services: Services;
        options: BackendOptions;
        constructor(services?: Services, options?: BackendOptions);
        init(services?: Services, options?: BackendOptions): void;
        readMulti(languages: any[], namespaces: any[], callback: Function): void;
        read(language: {}, namespace: {}, callback: Function): void;
        loadUrl(url: string, callback: Function): void;
        create(languages: any[], namespace: string, key: string, fallbackValue: string): void;
    }
}
