// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/28ef3d201b4271f3bb6c417b01a98d5706dd62a5/pouchdb-adapter-fruitdown/index.d.ts
declare namespace PouchDB {
    namespace FruitDOWNAdapter {
        interface FruitDOWNAdapterConfiguration
                extends Configuration.LocalDatabaseConfiguration {
            adapter: 'fruitdown';
        }
    }

    interface Static {
        new<Content extends Core.Encodable>(name: string | void,
            options: FruitDOWNAdapter.FruitDOWNAdapterConfiguration
            ): Database<Content>;
    }
}

declare module 'pouchdb-adapter-fruitdown' {
    const plugin: PouchDB.Plugin;
    export = plugin;
}
