// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a396c170ba4b6a7f45b20fccbdba0d2b81cc8833/pouchdb-adapter-node-websql/pouchdb-adapter-node-websql.d.ts
declare module 'pouchdb-adapter-node-websql' {
    const plugin: PouchDB.Plugin;
    export = plugin;
}
