// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/28ef3d201b4271f3bb6c417b01a98d5706dd62a5/pouchdb-adapter-leveldb/index.d.ts
declare namespace PouchDB {
    namespace LevelDbAdapter {
        interface LevelDbAdapterConfiguration extends Configuration.LocalDatabaseConfiguration {
            adapter: 'leveldb';
        }
    }

    interface Static {
        new<Content extends Core.Encodable>(name: string | void,
            options: LevelDbAdapter.LevelDbAdapterConfiguration
            ): Database<Content>;
    }
}

declare module 'pouchdb-adapter-leveldb' {
    const plugin: PouchDB.Plugin;
    export = plugin;
}
