// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/28ef3d201b4271f3bb6c417b01a98d5706dd62a5/pouchdb-adapter-http/index.d.ts
declare namespace PouchDB {
    namespace HttpAdapter {
        interface HttpAdapterConfiguration
                extends Configuration.RemoteDatabaseConfiguration {
            adapter: 'http';
        }
    }

    interface Static {
        new<Content extends Core.Encodable>(name: string | void,
            options: HttpAdapter.HttpAdapterConfiguration
            ): Database<Content>;
    }
}

declare module 'pouchdb-adapter-http' {
    const plugin: PouchDB.Plugin;
    export = plugin;
}
